version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: planes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  module1:
    build:
      context: .
      dockerfile: module1/Dockerfile
    container_name: module1
    ports:
      - "50051:50051"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      PROTO_PATH: /app/proto/plane.proto
    depends_on:
      rabbitmq:
        condition: service_healthy

  module2:
    build:
      context: .
      dockerfile: module2/Dockerfile
    container_name: module2
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/planes_db
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
